This is makeindex, version 2.15 [MiKTeX 21.8].
Scanning style file ./memoirthesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file memoirthesis.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (11 comparisons).
Generating output file memoirthesis.acr....done (9 lines written, 0 warnings).
Output written in memoirthesis.acr.
Transcript written in memoirthesis.alg.
